# Generated by Django 4.2.4 on 2023-08-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_comment_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
