# Generated by Django 4.2.4 on 2023-08-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
