# Generated by Django 4.2.1 on 2023-08-12 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0012_post_bookmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="post_like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
